// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Sidebar dedicated to the second docs plugin instance (docs2/ directory).
// Docs plugin instances must NOT share the same sidebar file: each instance
// generates a sidebar for every key it finds, which leads to name clashes.
/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorial2Sidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
